version: '2.1'

services:
  mysql-host:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./db/init/:/docker-entrypoint-initdb.d/
    command: ["--default-authentication-plugin=mysql_native_password"]

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://$DBHOST/$DBNAME?useSsl=false -user=$DBUSER -password=$DBPASS migrate -connectRetries=30
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - mysql-host
  app:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-host


volumes:
  mysql-db:




